configuration:
  - Debug
  - Release

environment:
  TreatWarningsAsErrors: true

branches:
  only:
    - master
    - develop

skip_tags: true

notifications:
  - provider: GitHubPullRequest
    on_build_success: true
    on_build_failure: true

cache:
  - packages -> **\packages.config

before_build:
  - nuget restore

after_build:
  - 7z a bin\%CONFIGURATION%\Drop.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.exe
  - 7z a bin\%CONFIGURATION%\Drop.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.dll
  - 7z a bin\%CONFIGURATION%\Drop.zip %APPVEYOR_BUILD_FOLDER%\bin\%CONFIGURATION%\*.pdb

test:
  assemblies:
    - '**\bin\$(configuration)\*.test.dll'

artifacts:
  - path: bin\$(configuration)
    name: Drop
    type: zip

# vim: set ai et st=2 sts=2 sw=2:
